import React,{useEffect,useRef,useState} from 'react';
import {createScene} from './scene.js';
import {loadSourcedMotorcycle} from './sourced-model.js';
import {PARTS} from './model.js';
import './fz6.css';
import {validateDetection} from './detection.js';
import BikeSwitcher from '../bikes/BikeSwitcher.jsx';
const icons={cube:<><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9Z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9M8 5.2l8 4.6"/></>,scan:<><path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5M3 12h18"/></>,rotate:<><path d="M20 10a8 8 0 1 0-2 8M20 4v6h-6"/></>,focus:<><path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/><circle cx="12" cy="12" r="3"/></>,layers:<><path d="m12 3 9 5-9 5-9-5Zm-9 9 9 5 9-5m-18 5 9 5 9-5"/></>,play:<path d="m8 5 11 7-11 7Z"/>,pause:<><path d="M8 5v14M16 5v14"/></>,chevron:<path d="m9 5 7 7-7 7"/>,photo:<><rect x="3" y="5" width="18" height="15" rx="3"/><path d="m3 16 5-5 5 5 3-3 5 5"/><circle cx="16" cy="9" r="1"/></>,close:<path d="m6 6 12 12M6 18 18 6"/>,download:<><path d="M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4"/></>,tool:<path d="M14 6a5 5 0 0 0-6 6L3 17a3 3 0 0 0 4 4l5-5a5 5 0 0 0 6-6l-4 3-3-3Z"/>};
function Icon({name,size=18}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">{icons[name]||icons.cube}</svg>;}
export default function FZ6(){const host=useRef(null),engine=useRef(null),anchor=useRef(null),photoInput=useRef(null),jsonInput=useRef(null);const[selected,setSelected]=useState(null),[mode,setMode]=useState('studio'),[explode,setExplode]=useState(0),[orbit,setOrbit]=useState(false),[progress,setProgress]=useState(0),[playing,setPlaying]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(''),[modal,setModal]=useState(false),[photo,setPhoto]=useState(null),[detection,setDetection]=useState(null),[color,setColor]=useState('#10257f'),[tab,setTab]=useState('parts'),[toast,setToast]=useState(''),[modelSource,setModelSource]=useState('procedural');
 const part=PARTS.find(p=>p.id===selected);const stage=progress<.08?0:progress<.26?1:progress<.43?2:progress<.60?3:progress<.84?4:5;
 useEffect(()=>{document.title='FZ6 / Motion Lab';let disposed=false;const favicon=document.createElement('link');favicon.rel='icon';favicon.href='/fz6/favicon.svg';document.head.appendChild(favicon);
 const start=async()=>{let model=null;if(import.meta.env.DEV){try{const r=await fetch('/fz6/local-model.glb',{method:'HEAD'});if(r.ok){setModelSource('loading');model=await loadSourcedMotorcycle();}}catch{setModelSource('procedural');}}if(disposed){model?.bike.traverse(o=>{o.geometry?.dispose();});model?.materialList.forEach(m=>m.dispose());return;}setModelSource(model?'s3d':'procedural');try{engine.current=createScene(host.current,{onSelect:setSelected,onProgress:setProgress,onPlaying:setPlaying,onReady:setReady,onAnchor:p=>{if(anchor.current){anchor.current.style.transform=`translate(${p.x+20}px,${p.y-32}px)`;anchor.current.style.visibility=p.visible?'visible':'hidden';}}},model);}catch(e){setError(`The 3D viewer could not start: ${e.message}`);}};start();return()=>{disposed=true;engine.current?.dispose();favicon.remove();};},[]);
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(id);},[toast]);
 useEffect(()=>{if(!photo)return;return()=>URL.revokeObjectURL(photo);},[photo]);
 function applyDetection(payload){validateDetection(payload);setDetection(payload);engine.current?.select(payload.partId,true);setTab('vision');return {ok:true,partId:payload.partId};}
 useEffect(()=>{window.fz6Viewer={selectPart:id=>engine.current?.select(id,true),applyDetection,playRepair:()=>{setExplode(0);engine.current?.play();},getParts:()=>PARTS.map(({id,name})=>({id,name}))};const listener=e=>{try{applyDetection(e.detail);}catch(e){setToast(e.message);}};window.addEventListener('fz6:detection',listener);return()=>{delete window.fz6Viewer;window.removeEventListener('fz6:detection',listener);};},[]);
 function switchMode(v){setMode(v);engine.current?.setMode(v);}function reset(){engine.current?.reset();setExplode(0);setOrbit(false);setDetection(null);}
 function play(){setExplode(0);engine.current?.play();}function capture(){const a=document.createElement('a');a.href=engine.current.capture();a.download='yamaha-fz6-motion-lab.png';a.click();setToast('Studio image saved');}
 async function loadPhoto(e){const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('image/'))return setToast('Choose an image file');setPhoto(URL.createObjectURL(f));setDetection(null);setTab('vision');e.target.value='';}
 async function loadJson(e){const f=e.target.files?.[0];if(!f)return;try{applyDetection(JSON.parse(await f.text()));setToast('Detection mapped to 3D component');}catch(err){setToast(err.message);}e.target.value='';}
 return <div className="motion-lab"><header className="lab-header"><a className="lab-brand" href="/fz6"><span className="brand-symbol"><Icon name="layers" size={22}/></span><span>MOTION<span className="brand-light"> / LAB</span></span></a><BikeSwitcher/><button className="reference-button" onClick={()=>setModal(true)}><Icon name="photo" size={15}/> Reference library <span>↗</span></button></header>
 <main className="lab-main"><section className="viewport"><div ref={host} className="canvas-host" aria-label="Interactive Yamaha FZ6 motorcycle. Drag to orbit, scroll to zoom, right-drag to pan."/><div className="model-heading"><div className="eyebrow">YAMAHA MOTOR CO. <span> / </span> {modelSource==='s3d'?'2008 / EXTERIOR STUDY':'2007 / 4S81 STUDY'}</div><h1>FZ6<span>FAZER S2</span></h1><p>Explore the assembly. Check the evidence.</p></div><div className="scene-status"><span className="status-dot"/> {ready?'LIVE 3D':modelSource==='loading'?'LOADING DETAILED MESH':'BUILDING MODEL'}<span className="scene-status-note">{modelSource==='s3d'?'DETAILED COMPONENT STUDY':'REFERENCE-BUILT STUDY'}</span></div>
 {error&&<div className="viewer-error">{error}<button onClick={()=>location.reload()}>Try again</button></div>}
 <div className="vertical-tools"><button title="Reset camera and animation" onClick={reset}><Icon name="rotate"/></button><button title="Focus selected part" disabled={!selected} onClick={()=>engine.current?.select(selected,true)}><Icon name="focus"/></button><button title="Auto rotate" className={orbit?'active':''} onClick={()=>{setOrbit(!orbit);engine.current?.setOrbit(!orbit);}}><span className="orbit-icon">↻</span></button><span/><button title="Save a studio image" onClick={capture} disabled={!ready}><Icon name="download"/></button></div>
 {selected&&<div ref={anchor} className="part-anchor"><span/><button onClick={()=>engine.current?.select(selected,true)}>{part?.name}<Icon name="chevron" size={12}/></button></div>}
 {modelSource==='s3d'&&<a className="source-credit" href="/fz6/parts">S3D components + procedural bodywork · local evaluation ↗</a>}<div className="viewport-bottom"><div className="view-presets">{[['hero','Perspective'],['side','Side'],['front','Front'],['rear','Rear'],['top','Top']].map(([id,name])=><button key={id} onClick={()=>engine.current?.view(id)}>{name}</button>)}</div><div className="interaction-hint"><span>↔</span> Drag to orbit <i/> Scroll to zoom <i/> Click a part</div></div><div className="scale-mark"><span/>1,440 mm wheelbase<span/></div>
 </section><aside className="inspector"><div className="inspector-top"><span className="eyebrow">THE MACHINE</span><span className="model-code">FZ6—S2</span></div><div className="inspector-title"><h2>Built to be explored.</h2><p>Photo-referenced exterior · S2 component inventory.</p></div><div className="specs"><div><strong>600<span>cc</span></strong><small>INLINE FOUR</small></div><div><strong>72<span>kW</span></strong><small>AT 12,000 RPM</small></div><div><strong>6<span>speed</span></strong><small>TRANSMISSION</small></div></div>
 <div className="render-section"><label className="section-label">RENDER MODE</label><div className="mode-switch">{[['studio','cube','Studio'],['xray','scan','X-ray'],['wireframe','layers','Mesh']].map(([id,icon,name])=><button key={id} className={mode===id?'active':''} onClick={()=>switchMode(id)}><Icon name={icon} size={15}/>{name}</button>)}</div><div className="paint-row"><span>Paint finish</span><div>{[['#10257f','Yamaha blue'],['#aab2bd','Silver'],['#a61725','Red'],['#20252c','Graphite']].map(([c,name])=><button title={name} aria-label={name} key={c} className={color===c?'chosen':''} style={{'--swatch':c}} onClick={()=>{setColor(c);engine.current?.setColor(c);}}/>)}</div></div><div className="explode-label"><label htmlFor="explode">Exploded assembly</label><span>{Math.round(explode*100)}%</span></div><input id="explode" type="range" min="0" max="1" step=".01" value={explode} onChange={e=>{let v=+e.target.value;setExplode(v);engine.current?.setExplode(v);}}/></div>
 <div className="inspector-tabs"><button className={tab==='parts'?'active':''} onClick={()=>setTab('parts')}>Components <span>10</span></button><button className={tab==='vision'?'active':''} onClick={()=>setTab('vision')}><Icon name="scan" size={14}/> Vision bridge</button></div>
 {tab==='parts'?<div className="component-list">{PARTS.map((p,i)=><button key={p.id} className={`component ${selected===p.id?'selected':''}`} onClick={()=>engine.current?.select(p.id,true)}><span className="part-number">{String(i+1).padStart(2,'0')}</span><span><strong>{p.name}</strong><small>{p.system}</small></span><Icon name="chevron" size={13}/></button>)}</div>:<div className="vision-panel"><span className="vision-label">IMAGE → PART → MOTION</span><p>Map detections from your CV pipeline to named 3D components.</p><button className="image-upload" onClick={()=>photoInput.current.click()}>{photo?<img src={photo} alt="Your motorcycle reference"/>:<><Icon name="photo" size={24}/><span>Add a motorcycle photo</span><small>Stays in your browser</small></>}{photo&&detection?.bbox&&<span className="detection-box" style={{left:`${detection.bbox[0]*100}%`,top:`${detection.bbox[1]*100}%`,width:`${detection.bbox[2]*100}%`,height:`${detection.bbox[3]*100}%`}}/>}</button><div className="vision-actions"><button onClick={()=>jsonInput.current.click()}>Import detection JSON</button><button onClick={()=>applyDetection({partId:'front-brake',confidence:.96,source:'simulated'})}>Try sample</button></div>{detection&&<div className="detection-result"><span className="status-dot"/><strong>{PARTS.find(p=>p.id===detection.partId)?.name}</strong><small>{detection.confidence!=null?`${Math.round(detection.confidence*100)}% · `:''}{detection.source==='simulated'?'Simulated detection':'Imported detection'}</small>{detection.partId==='front-brake'&&<button onClick={play}>Preview caliper animation →</button>}</div>}<p className="vision-note">Detection input is supported. Automatic image recognition and photo-to-3D alignment are not connected yet.</p><code>{'{ "partId": "front-brake",\n  "confidence": 0.96,\n  "bbox": [0.6, 0.5, 0.1, 0.2] }'}</code></div>}
 <a className="parts-evidence-link" href="/fz6/parts">OEM parts & internal assembly evidence <span>↗</span></a><div className="selected-description"><span className="status-dot"/><p>{part?part.description:'Select a component on the model or in the list to inspect it.'}</p></div></aside></main>
 <section className="repair-dock"><div className="repair-title"><span className="repair-icon"><Icon name="tool" size={21}/></span><div><span className="eyebrow">MOTION STUDY <span className="demo-tag">DEMO</span></span><h3>Front caliper · internal assembly</h3><p>Exploded inventory · geometry unverified</p></div></div><div className="timeline"><div className="timeline-steps">{['Assembled','Separate','Retainers','Internal parts','Return','Assembled'].map((s,i)=><button key={i} className={stage===i?'current':stage>i?'complete':''} onClick={()=>{setExplode(0);engine.current?.setExplode(0);engine.current?.select('front-brake',true);engine.current?.setProgress([0,.12,.30,.49,.71,1][i]);}}><span>{String(i+1).padStart(2,'0')}</span>{s}</button>)}</div><input aria-label="Repair animation timeline" type="range" min="0" max="1" step=".001" value={progress} style={{'--progress':`${progress*100}%`}} onChange={e=>{engine.current?.select('front-brake');engine.current?.setProgress(+e.target.value);}}/><div className="timeline-time"><span>{(progress*14).toFixed(1)}s</span><span>14.0s</span></div></div><button className="play-button" disabled={!ready} onClick={play}><Icon name={playing?'pause':'play'} size={17}/>{playing?'Pause':'Play study'}</button></section>
 <footer className="lab-footer"><span><span className="status-dot"/> THREE.JS <i/> PBR MATERIALS <i/> PART-AWARE GEOMETRY</span><span>FROM OBSERVATION TO UNDERSTANDING <span className="footer-arrow">↗</span></span></footer>
 <input ref={photoInput} type="file" accept="image/*" hidden onChange={loadPhoto}/><input ref={jsonInput} type="file" accept="application/json,.json" hidden onChange={loadJson}/>
 {toast&&<div role="status" className="toast">{toast}</div>}
 {modal&&<div className="modal-scrim" onClick={()=>setModal(false)}><section role="dialog" aria-modal="true" aria-label="Reference library" className="reference-modal" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setModal(false);}}><button autoFocus className="close-modal" onClick={()=>setModal(false)} aria-label="Close references"><Icon name="close"/></button><span className="eyebrow">REFERENCE LIBRARY</span><h2>Rooted in the real thing.</h2><a href="/fz6/parts">Browse 46 OEM assemblies, internal parts and third-party models →</a><a href="/fz6/compare">Compare source photos against matched-angle renders →</a><img src="/fz6/yamaha-reference.jpg" alt="Yamaha's official blue 2007 FZ6 Fazer S2 studio photograph"/><p>This viewer studies the FZ6 Fazer S2 using Yamaha’s release, studio photography and catalogue. The local detailed exterior uses Satyam/S3D’s 2008 FZ6 mesh when installed. Materials are adapted for glTF. The fallback exterior and caliper study are procedural approximations. Other internal assemblies are documented in the parts browser but have no validated meshes.</p><a href="https://global.yamaha-motor.com/news/2006/1010/fz6-fazer.html" target="_blank" rel="noreferrer">Yamaha · 2007 FZ6 Fazer spec2 release & specifications ↗</a><a href="https://global.yamaha-motor.com/news/2003/0821/fz6.html" target="_blank" rel="noreferrer">Yamaha · engine, aluminum frame & exhaust architecture ↗</a><a href="https://www.1000ps.de/modellnews-id-1916313-yamaha-fz6-s2-2007" target="_blank" rel="noreferrer">1000PS · FZ6 S2 studio reference photos ↗</a><small>Reference photograph © Yamaha Motor Co., Ltd. Displayed for reference; no affiliation.</small></section></div>}
 </div>;
}
