import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { createMotorcycle, PARTS } from './model.js';
export function createScene(host, callbacks={}, suppliedModel=null) {
 const scene=new THREE.Scene();scene.background=new THREE.Color('#101519');scene.fog=new THREE.Fog('#101519',6,16);
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;host.appendChild(renderer.domElement);
 const camera=new THREE.PerspectiveCamera(34,1,.02,40);camera.position.set(2.5,1.55,3.05);
 const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.57,0);controls.enableDamping=true;controls.dampingFactor=.065;controls.minDistance=.5;controls.maxDistance=6;controls.maxPolarAngle=Math.PI*.49;controls.autoRotateSpeed=.55;controls.enablePan=true;
 const pmrem=new THREE.PMREMGenerator(renderer);const room=new RoomEnvironment();const environment=pmrem.fromScene(room,.05);scene.environment=environment.texture;scene.environmentIntensity=.65;room.dispose();pmrem.dispose();
 scene.add(new THREE.HemisphereLight('#bddeff','#2c3338',1.3));
 function area(x,y,z,color,intensity){let l=new THREE.DirectionalLight(color,intensity);l.position.set(x,y,z);scene.add(l);return l;}
 const key=area(2,4,3,'#e0ebff',4);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-2;key.shadow.camera.right=2;key.shadow.camera.top=2;key.shadow.camera.bottom=-2;key.shadow.normalBias=.025;key.shadow.bias=-.0001;key.shadow.radius=4;area(-2,2,-3,'#779bff',4);area(-3,1,2,'#d8fce9',2);
 const model=suppliedModel||createMotorcycle();scene.add(model.bike);
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(100,100),new THREE.MeshStandardMaterial({color:'#080d10',roughness:.94,metalness:.08}));floor.rotation.x=-Math.PI/2;floor.position.y=-.007;floor.receiveShadow=true;scene.add(floor);
 const grid=new THREE.Mesh(new THREE.PlaneGeometry(10,10),new THREE.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{uColor:{value:new THREE.Color('#637a78')}},vertexShader:'varying vec2 vUv; void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 vUv;uniform vec3 uColor;void main(){vec2 p=(vUv-.5)*50.; vec2 q=abs(fract(p-.5)-.5)/fwidth(p);float line=1.-min(min(q.x,q.y),1.);float fade=1.-smoothstep(.06,.4,length(vUv-.5));gl_FragColor=vec4(uColor,line*fade*.22);}'}));grid.rotation.x=-Math.PI/2;grid.position.y=-.004;scene.add(grid);
 const shadowCanvas=document.createElement('canvas');shadowCanvas.width=256;shadowCanvas.height=256;const cx=shadowCanvas.getContext('2d');let grad=cx.createRadialGradient(128,128,5,128,128,125);grad.addColorStop(0,'rgba(0,0,0,.7)');grad.addColorStop(1,'rgba(0,0,0,0)');cx.fillStyle=grad;cx.fillRect(0,0,256,256);const contact=new THREE.Mesh(new THREE.PlaneGeometry(2.7,1.25),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(shadowCanvas),transparent:true,depthWrite:false}));contact.rotation.x=-Math.PI/2;contact.position.y=-.002;scene.add(contact);
 const xray=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,uniforms:{time:{value:0},color:{value:new THREE.Color('#73bda6')}},vertexShader:'varying vec3 vN;varying vec3 vV;varying vec3 vW;void main(){vec4 p=modelViewMatrix*vec4(position,1.);vN=normalize(normalMatrix*normal);vV=normalize(-p.xyz);vW=(modelMatrix*vec4(position,1.)).xyz;gl_Position=projectionMatrix*p;}',fragmentShader:'uniform float time;uniform vec3 color;varying vec3 vN;varying vec3 vV;varying vec3 vW;void main(){float rim=pow(1.-abs(dot(normalize(vN),normalize(vV))),2.3);float line=pow(.5+.5*sin(vW.y*160.-time*2.),16.);float scan=exp(-pow((vW.y-mod(time*.25,1.8))*15.,2.));gl_FragColor=vec4(color*(.45+rim+scan*.7),.055+rim*.3+line*.035+scan*.1);}'});
 const highlight=new THREE.MeshPhysicalMaterial({color:'#79dabc',metalness:.5,roughness:.25,emissive:'#45bc91',emissiveIntensity:.32});
 let mode='studio',selected=null,explode=0,explodeActual=0,progress=0,playing=false,animation=0,last=performance.now(),cameraTween=null,disposed=false,frameCount=0;
 const meshes=[];model.bike.traverse(o=>{if(o.isMesh)meshes.push(o);});
 function materials(){meshes.forEach(o=>{o.material=mode==='xray'?(o.userData.partId===selected?highlight:xray):o.userData.originalMaterial;if(mode!=='xray'){const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{m.wireframe=mode==='wireframe';});}});}
 const ring=new THREE.Mesh(new THREE.TorusGeometry(.105,.0015,8,72),new THREE.MeshBasicMaterial({color:'#8de4bd',transparent:true,opacity:.65,depthTest:false}));ring.visible=false;scene.add(ring);
 function fly(position,target){cameraTween={from:camera.position.clone(),to:new THREE.Vector3(...position),tf:controls.target.clone(),tt:new THREE.Vector3(...target),start:performance.now()};}
 function select(id,focus=false){selected=PARTS.some(p=>p.id===id)?id:null;materials();callbacks.onSelect?.(selected);if(selected&&focus){let p=PARTS.find(p=>p.id===id).position;let z=id==='exhaust'?-1.35:1.45;fly([p[0]+.65,p[1]+.42,z],p);}ring.visible=!!selected;}
 function setRepair(value){progress=Math.max(0,Math.min(1,value));if(!Number.isFinite(progress))progress=0;callbacks.onProgress?.(progress);}
 function view(v){const views={hero:[[2.5,1.55,3.05],[0,.57,0]],side:[[.02,.80,3.5],[0,.56,0]],front:[[3.5,1.05,.02],[.1,.61,0]],rear:[[-3.5,1.2,1.3],[-.1,.61,0]],top:[[.01,3.7,.01],[0,.5,0]]};if(views[v])fly(...views[v]);}
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let down=null;
 const onDown=e=>{down=[e.clientX,e.clientY];cameraTween=null;};
 const onUp=e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(meshes,false).find(h=>{let o=h.object;while(o){if(!o.visible)return false;o=o.parent;}return true;});if(hit)select(hit.object.userData.partId);};
 renderer.domElement.addEventListener('pointerdown',onDown);renderer.domElement.addEventListener('pointerup',onUp);
 const onDbl=()=>{if(selected)select(selected,true);};renderer.domElement.addEventListener('dblclick',onDbl);
 const resize=new ResizeObserver(()=>{const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();});resize.observe(host);
 const smooth=(a,b,v)=>{const t=THREE.MathUtils.clamp((v-a)/(b-a),0,1);return t*t*(3-2*t);};
 function tick(now){if(disposed)return;animation=requestAnimationFrame(tick);let dt=Math.min((now-last)/1000,.05);last=now;xray.uniforms.time.value=now/1000;
 if(cameraTween){let t=Math.min(1,(now-cameraTween.start)/950),s=t*t*(3-2*t);camera.position.lerpVectors(cameraTween.from,cameraTween.to,s);controls.target.lerpVectors(cameraTween.tf,cameraTween.tt,s);if(t===1)cameraTween=null;}
 explodeActual=THREE.MathUtils.damp(explodeActual,explode,5,dt);PARTS.forEach(p=>model.groups[p.id].position.set(...p.explode.map(x=>x*explodeActual)));
 if(playing){progress=Math.min(1,progress+dt/14);callbacks.onProgress?.(progress);if(progress===1){playing=false;callbacks.onPlaying?.(false);}}
 const out=smooth(.08,.26,progress)*(1-smooth(.77,.96,progress));model.repair.bolts.forEach((b,i)=>{b.position.z=b.userData.baseZ+out*.15;b.rotation.z=out*Math.PI*2*(i?1:-1);});
 model.setStudyProgress?.(progress);
 const detail=smooth(.08,.55,progress)*(1-smooth(.70,1,progress));model.repair.details.forEach(a=>a.explode(detail));
 if(selected){const p=PARTS.find(p=>p.id===selected);ring.position.copy(new THREE.Vector3(...p.position)).add(model.groups[selected].position);ring.quaternion.copy(camera.quaternion);ring.material.opacity=.45+Math.sin(now*.002)*.15;const pos=ring.position.clone().project(camera);callbacks.onAnchor?.({x:(pos.x*.5+.5)*host.clientWidth,y:(-.5*pos.y+.5)*host.clientHeight,visible:pos.z<1});}
 controls.update();renderer.render(scene,camera);if(++frameCount===30){callbacks.onReady?.({meshes:meshes.length,triangles:renderer.info.render.triangles,source:model.source||'procedural'});} }
 animation=requestAnimationFrame(tick);
 const api={select,view,setMode(v){mode=v;materials();},setExplode(v){explode=Math.max(0,Math.min(1,v));},setColor(c){model.setPaint(c);},setOrbit(v){controls.autoRotate=v;},setProgress(v){playing=false;callbacks.onPlaying?.(false);setRepair(v);},play(){select('front-brake',true);explode=0;if(progress>=1)progress=0;playing=!playing;callbacks.onPlaying?.(playing);},reset(){progress=0;playing=false;explode=0;controls.autoRotate=false;callbacks.onProgress?.(0);callbacks.onPlaying?.(false);select(null);view('hero');},capture(){renderer.render(scene,camera);return renderer.domElement.toDataURL('image/png');},dispose(){disposed=true;cancelAnimationFrame(animation);resize.disconnect();controls.dispose();renderer.domElement.removeEventListener('pointerdown',onDown);renderer.domElement.removeEventListener('pointerup',onUp);renderer.domElement.removeEventListener('dblclick',onDbl);const geometries=new Set(),materialsSet=new Set(),textures=new Set();scene.traverse(o=>{if(o.geometry)geometries.add(o.geometry);if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>materialsSet.add(m));if(o.userData.originalMaterial)materialsSet.add(o.userData.originalMaterial);});geometries.forEach(g=>g.dispose());materialsSet.forEach(m=>{Object.values(m).forEach(v=>{if(v?.isTexture)textures.add(v);});m.dispose();});textures.forEach(t=>t.dispose());environment.dispose();renderer.dispose();renderer.domElement.remove();}};
 return api;
}
