import React, {useEffect, useRef, useState} from 'react';

export default function DamageCase({example, ready, configured, onStep}) {
  const [photoIndex,setPhotoIndex]=useState(0),[step,setStep]=useState(0),[playing,setPlaying]=useState(false);
  const [live,setLive]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const controller=useRef(null),onStepRef=useRef(onStep);onStepRef.current=onStep;
  useEffect(()=>()=>controller.current?.abort(),[]);
  useEffect(()=>{
    if(!playing)return;
    const timer=setTimeout(()=>{
      if(step===example.steps.length-1){setPlaying(false);return;}
      setStep(step+1);onStepRef.current(example.steps[step+1]);
    },6500);
    return()=>clearTimeout(timer);
  },[playing,step,example]);
  function jump(index){setPlaying(false);setStep(index);onStep(example.steps[index]);}
  function play(){if(playing)return setPlaying(false);const index=step===example.steps.length-1?0:step;setStep(index);onStep(example.steps[index]);setPlaying(true);}
  async function reanalyze(){
    controller.current?.abort();controller.current=new AbortController();setBusy(true);setError('');
    try {
      const response=await fetch(`/api/vehicles/examples/${example.id}/analyze`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({vehicleId:example.vehicleId}),signal:controller.current.signal});
      const data=await response.json();if(!response.ok)throw new Error(data.error||'Analysis unavailable.');setLive(data);
    }catch(e){if(e.name!=='AbortError')setError(e.message);}finally{setBusy(false);}
  }
  const photo=example.photos[photoIndex],analysis=live||example.analysis;
  const box=live&&photoIndex===0?live.bbox:photo.bbox;
  return <section className="damage-case" aria-label="Analyzed online damage example">
    <div className="eyebrow">ONLINE PHOTO → AI ASSESSMENT → REPAIR REVIEW</div>
    <h3>{example.title}</h3><p className="damage-case-subtitle">{example.subtitle}</p>
    <figure className="damage-photo"><div><img src={photo.src} alt={photo.label}/>{box&&<span className="damage-annotation" style={{left:`${box[0]*100}%`,top:`${box[1]*100}%`,width:`${box[2]*100}%`,height:`${box[3]*100}%`}}><span>AREA TO INSPECT</span></span>}</div><figcaption>{photo.label} · approximate image annotation</figcaption></figure>
    <div className="damage-photo-options">{example.photos.map((item,i)=><button key={item.id} aria-pressed={photoIndex===i} onClick={()=>setPhotoIndex(i)}>{i===0?'Close-up':'Wider angle'}</button>)}</div>
    <a className="damage-credit" href={example.source.url} target="_blank" rel="noreferrer">{example.source.credit} · original report ↗</a>
    <div className="damage-analysis"><span className="damage-analysis-label">{live?`LIVE OPENAI ANALYSIS · ${live.model}`:'SAVED CODEX IMAGE ANALYSIS'}</span><p>{analysis.observations}</p><h4>Likely problem</h4><p>{analysis.diagnosis}</p><small>{analysis.uncertainty}</small><p className="damage-next-check">{analysis.nextCheck}</p></div>
    <details className="damage-provenance"><summary>How this was analyzed</summary><p>The saved assessment was produced by Codex after visually reviewing both source photographs. It was not generated by the app’s live API. It is an informed image assessment, not a confirmed mechanical diagnosis.</p><button className="repair-primary secondary" disabled={!configured||busy} onClick={reanalyze}>{busy?'Analyzing both photos…':'Re-analyze with OpenAI'}</button><small>{configured?'Sends the two public example photos to the configured OpenAI model.':'Live re-analysis needs OPENAI_API_KEY on the server. The saved review is available now.'}</small>{error&&<p role="alert" className="repair-error">{error}</p>}</details>
    <div className="damage-fix"><div className="eyebrow">PROPOSED FIX · INSPECTION REQUIRED</div><h4>{example.fix.title}</h4><p>{example.fix.recommendation}</p><a href={example.fix.source.url} target="_blank" rel="noreferrer">{example.fix.source.title} ↗</a><small>{example.fix.documentation}</small></div>
    <div className="damage-walkthrough"><button className="repair-primary" disabled={!ready} onClick={play}>{playing?'Ⅱ Pause 3D walkthrough':'▶ Play 3D walkthrough'}</button><small>Actual source assemblies · inspection tour, not repair execution</small><ol className="repair-steps">{example.steps.map((item,i)=><li key={item.title} className={step===i?'current':''}><button disabled={!ready} aria-current={step===i?'step':undefined} onClick={()=>jump(i)}><span>{String(i+1).padStart(2,'0')}</span>{item.title}</button>{step===i&&<p>{item.text}</p>}</li>)}</ol></div>
    <details className="repair-tools"><summary>Equipment for the proposed repair</summary>{example.fix.tools.map(tool=><div key={tool.name}><span>↗</span><p><strong>{tool.name}</strong><small>{tool.note}</small></p></div>)}</details>
    <p className="damage-mapping-note">{example.mapping.explanation}</p>
  </section>;
}
